Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "calico-2"
  config.vm.network "private_network", ip: "192.168.50.3"
  config.vm.provision "shell", path: "provision.sh"
end
